---
title: "GeneFishing - random"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{GeneFishing}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
library(GeneFishing)
library(MASS)
library(tidyverse)

set.seed(190)
# generate two random clouds of data
X <- rbind(mvrnorm(20, mu = c(5, 5, 1), 
                   Sigma = diag(rep(0.5, 3))), 
           mvrnorm(100, mu = c(1, 1, 1), 
                   Sigma = diag(rep(1, 3))))

rownames(X) <- paste0("R", 1:nrow(X))

# use 10 of the smaller cloud as "bait"
bait <- sample(paste0("R", 1:20), 15)

ggplot() + 
  geom_point(aes(x = X[, 1], y = X[, 2], 
                 color = ifelse(rownames(X) %in% bait, "bait", "not bait")), 
             alpha = 0.5) + 
  theme_classic() + 
  scale_color_discrete(name = "bait", direction = -1)
```

## Do GeneFishing
```{r}
fishing_results <- geneFishing(X, bait, method = "euclidean", alpha = 3,
                               fishing_rounds = 100, n_probing_rounds = 50)

fishing_results
```

```{r}
plot(fishing_results)
```


## Using correlation
From [this website](https://stats.stackexchange.com/questions/15011/generate-a-random-variable-with-a-defined-correlation-to-an-existing-variables) 
```{r}
# generate data that has the desired correlation structure 
generateVectorWithProvidedCor <- function(x_orig, rho, mu, sigma){
  theta <- acos(rho) 
  n <- length(x_orig)
  
  # randomly generate new vector
  x_new <- rnorm(n, mu, sigma)
  
  # center data
  X_centered  <- scale(cbind(x_orig, x_new), center = TRUE, scale = FALSE)
  
   # Q matrix from QR-decomposition
  Q <- qr.Q(qr(X_centered[, 1, drop = FALSE]))
  x2o <- (diag(n) - tcrossprod(Q)) %*% X_centered[, 2]
  Xc2 <- cbind(X_centered[, 1], x2o)
  
  # scale columns to length 1
  Y <- Xc2 %*% diag(1 / sqrt(colSums(Xc2 ^ 2)))
  
  return(Y[ , 2] + (1 / tan(theta)) * Y[ , 1])
}

# number of features (cells in data)
set.seed(2937)
n <- 100
x_orig_non_bait <- rnorm(n, 0, 1)
# make potential bait slightly correlated with non-bait genes
x_orig_potential_bait <- generateVectorWithProvidedCor(
  x_orig_non_bait, 0.1, 0, 1)
non_bait_genes <- sapply(1:150, function(i){
  generateVectorWithProvidedCor(x_orig_non_bait, 0.6, 0, 1)
}) %>% t()

potential_bait_genes <- sapply(1:20, function(i){
  generateVectorWithProvidedCor(x_orig_potential_bait, 0.6, 0, 1)
}) %>% t()

X <- rbind(potential_bait_genes, non_bait_genes)
rownames(X) <- paste0("R", 1:nrow(X))

# randomly sample 15 of the 20 potential bait genes to be used as actual 
# bait
bait <- sample(rownames(X)[1:20], 15)

cor_mat <- cor(t(X), method = "spearman")
coord <- getSpectralCoordinates(cor_mat, 2)$coordinates

ggplot(coord %>% data.frame() %>% rownames_to_column(var = "gene") %>%
         mutate(bait = ifelse(gene %in% bait, "yes", "no"))) + 
  geom_point(aes(x = eigen.1, y = eigen.2, color = bait), alpha = 0.5) + 
  theme_classic() + 
  scale_color_discrete(name = "bait", direction = -1)
```


```{r}
fishing_results <- geneFishing(X, bait, method = "spearman", alpha = 3,
                               fishing_rounds = 100, n_probing_rounds = 50, 
                               umap = FALSE)

fishing_results
```


```{r}
plot(fishing_results)
```

